CREATE DATABASE IF NOT EXISTS aeroporto;
USE aeroporto;

CREATE TABLE IF NOT EXISTS passageiro(
idPassageiro INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nomePassageiro CHAR(30) NOT NULL,
fonePassageiro CHAR(20)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS voo(
idVoo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
numeroVoo CHAR(30) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS lk_passageiro_voo(
idPassageiroVoo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idPassageiro INT NOT NULL,
idVoo INT NOT NULL,
checkout_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
return_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PassageiroVoo_Passageiro FOREIGN KEY(idPassageiro) REFERENCES passageiro(idPassageiro) ON DELETE CASCADE,
CONSTRAINT FK_PassageiroVoo_Voo FOREIGN KEY(idVoo) REFERENCES voo(idVoo) ON DELETE RESTRICT
)ENGINE=InnoDB;

DROP DATABASE IF EXISTS aeroporto;